#!/usr/bin/env python3
"""Generate src/entities.rs from the WHATWG named character reference list.

Usage:
    tools/gen-entities.py [entities.json]

With no argument the table is downloaded from
https://html.spec.whatwg.org/entities.json. Pass a path (or file:// URL) to
generate from a local copy instead.

Only the names that end in ';' are emitted: mdriver requires the trailing
semicolon, matching the HTML5 rules GFM references (and the behavior of the
`htmlentity` crate this table replaced). The ~106 legacy semicolon-less names
in entities.json are deliberately dropped.
"""

import json
import sys
import urllib.request

URL = "https://html.spec.whatwg.org/entities.json"

HEADER = """\
// @generated by tools/gen-entities.py -- do not edit by hand.
//
// Named character references from the WHATWG HTML spec's entities.json, the
// list GFM references. Only names with a trailing semicolon are included; see
// the generator for why.

/// Named HTML entities, sorted by name for binary search. Names include the
/// leading `&` and trailing `;`.
pub(crate) static NAMED_ENTITIES: &[(&str, &str)] = &[
"""

FOOTER = """];

/// Look up a named entity, e.g. `&amp;` -> `&`. The name must include the
/// leading `&` and trailing `;`.
pub(crate) fn lookup(name: &str) -> Option<&'static str> {
    NAMED_ENTITIES
        .binary_search_by(|(entity, _)| (*entity).cmp(name))
        .ok()
        .map(|idx| NAMED_ENTITIES[idx].1)
}
"""


def rust_str(value: str) -> str:
    """Render a Rust string literal. Printable characters are emitted as-is."""
    out = ['"']
    for ch in value:
        if ch in ('"', "\\"):
            out.append("\\" + ch)
        elif ch.isprintable():
            out.append(ch)
        else:
            out.append(f"\\u{{{ord(ch):x}}}")
    out.append('"')
    return "".join(out)


def load(source: str | None) -> dict[str, dict]:
    source = source or URL
    if "://" in source:
        with urllib.request.urlopen(source) as response:
            return json.load(response)
    with open(source, encoding="utf-8") as handle:
        return json.load(handle)


def main() -> None:
    if len(sys.argv) > 2:
        sys.exit(__doc__)
    entities = load(sys.argv[1] if len(sys.argv) > 1 else None)

    rows = sorted(
        (name, "".join(chr(cp) for cp in entry["codepoints"]))
        for name, entry in entities.items()
        if name.endswith(";")
    )

    lines = [HEADER]
    for name, value in rows:
        lines.append(f"    ({rust_str(name)}, {rust_str(value)}),\n")
    lines.append(FOOTER)

    sys.stdout.write("".join(lines))


if __name__ == "__main__":
    main()
